### PR TITLE
Rfi + cde benchmarking 2

### PR DESCRIPTION
**Pull request by Valentyn1997**
- Goodness-of-fit part of the benchmark (see green highlights of https://docs.google.com/document/d/1ESzqxrswKU8x1uwqG57CFt_4E-aYD3veFjfx5L2A3cc/edit)
- Mlflow+Hydra integration

### CODE REVIEW

**Review by gcskoenig — COMMENTED** [review]
- gaussian_estimator.py: Does sampling from the normal work also in 1d if we always use the multivariat normal function? Could you please validate? Why do you differentiate both cases for the conditional_distribution function? Is it necessary to rely on torch, requiring torch to work even if only gaussian sampling is to be used? Why do you remove checking whether it is a degenerate case? I would like that behaviour to persist! Also I want to sample the joint and not the individual dimensions, as discussed. We cannot merge before that is reverted.
- Renaming lots of stuff in the sampler class. trained_sampling_funcs is ok. _store_estimator function is really redundant, why??
- new hash functions, whats the use? 
- permuting values is the right phrasing in sample_perm
- rfi values is the right phrasing as well in explanation.py
- I ignore changes in explainer as I updated it, so I would not overwrite that with the changes you made (adapted to new sampler interface)
- I did not look into changes in modules/classes that only concern benchmark or cnf yet

**Comment by Valentyn1997** [comment]
> * gaussian_estimator.py: Does sampling from the normal work also in 1d if we always use the multivariat normal function? Could you please validate? Why do you differentiate both cases for the conditional_distribution function? Is it necessary to rely on torch, requiring torch to work even if only gaussian sampling is to be used? Why do you remove checking whether it is a degenerate case? I would like that behaviour to persist! Also I want to sample the joint and not the individual dimensions, as discussed. We cannot merge before that is reverted.
> * Renaming lots of stuff in the sampler class. trained_sampling_funcs is ok. _store_estimator function is really redundant, why??
> * new hash functions, whats the use?
> * permuting values is the right phrasing in sample_perm
> * rfi values is the right phrasing as well in explanation.py
> * I ignore changes in explainer as I updated it, so I would not overwrite that with the changes you made (adapted to new sampler interface)
> * I did not look into changes in modules/classes that only concern benchmark or cnf yet

1. I checked the validity while debugging, also np.random.multivatiate_normal documentation says about func parameters, that  "These parameters are analogous to the mean (average or "center") and variance (standard deviation, or "width," squared) of the one-dimensional normal distribution." 
Why do you differentiate both cases for the conditional_distribution function?  -> Just redundant piece of code - fixing it in the next commit.
Is it necessary to rely on torch, requiring torch to work even if only gaussian sampling is to be used? -> torch.distributions is a really powerful ready-to-use extension. They handle different conditional / unconditional distributions pretty well, so that we don't need to worry about all the shape issues.
Also I want to sample the joint and not the individual dimensions, as discussed. -> I will check it, when I write experiments for SAGE.
2. _store_estimator function is really redundant, why?? -> already deleted
3. new hash functions, whats the use? -> hash calculates the string representation of the run hparams of experiment, if I run many experiments and then some fail, I need to ignore already successfully finished runs and start from not yet performed. In principle, I could perform a search across all the params on MLflow server, but it turned out to be slow
4. rfi values is the right phrasing as well in explanation.py -> already merged it
5. I ignore changes in explainer as I updated it, so I would not overwrite that with the changes you made (adapted to new sampler interface) -> should be merged well now (I merged master to this branch)
6. I did not look into changes in modules/classes that only concern benchmark or cnf yet -> No worries

**Comment by Valentyn1997** [comment]
@gcskoenig - please review it 😁

**Comment by gcskoenig** [comment]
The branch is currently behind master, could you pull the recent Master changes? Then merging ok.

**Pull request merged**
